version: "3.8"

services:
  app:
    build: .
    container_name: tg-news-bot
    restart: always
    ports:
      - "8080:8080"
    environment:
      - TG_BOT_TOKEN=${TG_BOT_TOKEN}
      - NEWS_KEY=${NEWS_KEY}
    env_file:
      - .env

